name: padel_cup
description: "Padel Tournament Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  image_picker: ^1.1.0
  google_mlkit_text_recognition: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/padel.png"
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  adaptive_icon_background: "#1B5E20"
  adaptive_icon_foreground: "assets/padel.png"

flutter:
  generate: true
  uses-material-design: true
